### ISSUE TITLE
Como manipular o arquivo auxiliar?

### ISSUE THREAD

**Issue by robertorp** [pedrohlira/OpenPDV#1]
como manipular o arquivo auxiliar? por padrão ele veio com daruma, queria trocar pela bematec

**Comment by pedrohlira** [comment]
Olá, você deve alterar o arquivo https://github.com/pedrohlira/OpenPDV/blob/master/conf/auxiliar.properties da forma que precisar e usar o projeto https://github.com/pedrohlira/AdmPDV para criptografar este arquivo e assim ter como resultado o auxiliar.txt
