### ISSUE TITLE
Senha Criptografia

### ISSUE THREAD

**Issue by taliateli** [pedrohlira/OpenPDV#2]
Bom dia Pedro!
Qual a senha que devo informar ao criptografar os arquivos auxiliar.properties e banco.properties?

**Comment by pedrohlira** [comment]
Esta senha não posso lhe passar, você pode remover do código AdmPDV a necessidade desta senha, compilar novamente fazendo um novo jar e usar ele para criptografar e descriptografar os arquivos, lembre-se de usar o mesmo jar no projeto do OpenPDV e assim conseguirá usar sem precisar de senha.

**Comment by taliateli** [comment]
Ah sim, foi dessa forma que fiz mesmo. Tá ok
Muito obrigado!

Em 23 de outubro de 2015 10:03, Pedro Henrique de Lira <
notifications@github.com> escreveu:

**Comment by taliateli** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "Congresso Nacional: Em defesa das
Universidades Públicas Brasileiras" e queria saber se você pode ajudar
assinando também.

A nossa meta é conseguir 1.000.000 assinaturas e precisamos de mais apoio.
Você pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/9qKTKnbqG6

Obrigado!
Diego
